### ISSUE TITLE
Service dependente de uma model especifica

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#12]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Service/UserService.php#L9

Seu service n pode depender de uma model para ser usado, vc acaba criando um acoplamento mt grande e nem sempre vc vai usar a mesma instancia de User para fazer todas as operações da service

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
