### ISSUE TITLE
2 instancias de service sem necessidade

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#16]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Service/MessageService.php#L25

Você criou uma dependencia de objeto de model na sua service, logo toda vez q precisar validar ou testar objetos diferentes vai precisar instanciar um monte de service

Sua service deveria exigir dependencias nos proprios metodos e não de forma global (constructor), o que vc usa de forma global ai sim faz sentido

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
