### ISSUE TITLE
n existe esse metodo code validate

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#17]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Service/MessageService.php#L33

Essa validação de code validation n existe na userservice e essa regra é para ver se os codigos digitados para o ENVIO DA MENSAGEM são iguais, isso é uma regra da propria service de mensagem, vc pode validar diretamente lá 
```
if sender.code == receiver.code { return false } 
```

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
