### ISSUE TITLE
Dependencia desnecessaria

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#19]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Repository/UserRepository.php#L8

Não faz sentido depender de um determinado objeto de usuario, sua camada de acesso a dados precisa saber determinados atributos ou objetos de usuario em cada um de seus metodos, vc deve recebe-los nos metodos e n de forma global

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
