### ISSUE TITLE
showMessage? Papel da view

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#22]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Repository/MessageRepository.php#L22

showMessage não é um bom nome, fetchMessage, findMessage, findAllMessages....
vc n deve apresentar mensagens e sim resgatar a mensagem da fonte de dados (papel da sua repository)

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
