### ISSUE TITLE
identação??

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#24]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Repository/DatabaseRepository.php#L12

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/1977b5f777ba6d55023da02fc8f772a5d1ce8aee
