### ISSUE TITLE
Class fora da convenção

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#25]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Repository/DatabaseRepository.php#L3

Parece codigo copiado, arrume identação e convenções

Se vc entendeu o que se passa aqui parabéns ficou mt bom 👏
Caso n tenha entendido vamos conversar pra ficar claro

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/1977b5f777ba6d55023da02fc8f772a5d1ce8aee
