### ISSUE TITLE
Pq protected?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#26]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Models/Message.php#L5

Encapsulamento?
Estes atributos deveriam ser do próprio message não?

**Comment by joaoclopes** [comment]
Mas esse sender ta no message.
nao consegui entender esse

**Comment by jeansouzak** [comment]
Não entendi o que vc comentou.
Minha questão é relacionada aos modificadores de acesso, tbm o basico de POO, pq vc está usando um modificador de acesso "protected" nos seu atributos.
Outro pilar da orientação objeto encapsulamento, se isso não esta claro recomendo fortemente revisar os materiais, videos, pesquisar, praticar e perguntar.

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit
