### ISSUE TITLE
protected?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#27]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Models/User.php#L5

mesma questão da issue: https://github.com/joaoclopes/wrkoo/issues/26

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit
