### ISSUE TITLE
Sua controller recebe-ra estes parametros prontos?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#3]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Controller/MessageController.php#L15

Se a sua controller recebe estes parametros prontos quer dizer q alguem irá precisar resolve-los a partir da requisição para injetar neste metodo
Seu roteador/middleware precisará tratar disso ou vc faz a controller tratar a request normalmente para passar para a service

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/blob/master/App/RegisterMessage.php
