### ISSUE TITLE
A controller poderia lidar com esses parametros

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#30]
https://github.com/joaoclopes/wrkoo/blob/feb94c2fb1f9234ae95327803b46b800505f27f8/App/RegisterMessage.php#L7

Ou vc cria um middleware / interpretador de recursos da uri para passar para controller ou coloca isso na propria controller

**Comment by joaoclopes** [comment]
Mas colocar essa parte na controller nao deixaria o codigo mais feio?

**Comment by jeansouzak** [comment]
É responasbilidade da controller capturar o que chega para repassar para as demais camadas / responsabilidades do sistema, não é feio.
Como vc ta fazendo na mão sem uso de frameworks / pacotes para manusear suas rotas, vc deveria trabalhar em um mecanismo para extrair e passar isso para os metodos da controller de forma automatica, como um roteador, ficaria mt mais bonito, para o proximo projeto sem falta

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit, porém gostaria de conversar com voce sobre
