### ISSUE TITLE
Ta validando o que aqui?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#32]
https://github.com/joaoclopes/wrkoo/blob/feb94c2fb1f9234ae95327803b46b800505f27f8/Controller/MessageController.php#L18

Esse código provavelmente nem funciona, vc n passa os parametros, espera validar o q?

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/1977b5f777ba6d55023da02fc8f772a5d1ce8aee
