### ISSUE TITLE
pq 123 hardcoded?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#36]
https://github.com/joaoclopes/wrkoo/blob/1977b5f777ba6d55023da02fc8f772a5d1ce8aee/Controller/UserController.php#L15

**Comment by joaoclopes** [comment]
é uma coisa que meu irmão estava me explicando e acabei esquecendo de tirar, ja retirei la no proximo commit comento aqui

**Comment by jeansouzak** [comment]
está certo o conceito, porém o '123' direto no codigo n pode, vc ja tem o codigo da variavel

**Comment by joaoclopes** [comment]
Ajustado nesse commit 
https://github.com/joaoclopes/wrkoo/commit/3c85cebd6009230beb3dc06c83c3aa3887ddf32f
