### ISSUE TITLE
o que é isso??

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#37]
https://github.com/joaoclopes/wrkoo/blob/1977b5f777ba6d55023da02fc8f772a5d1ce8aee/Controller/MessageController.php#L27

1 - Sua model nem tem esse metodo
2 - nao faz sentido nenhum sua model ter isso
3 - oq isso faz???

**Comment by joaoclopes** [comment]
É para ver as mensagens, porém eu nao fiz a parte visual ainda, por isso nao se encaixa em nada no momento. Tem algum jeito melhor de fazer?

**Comment by jeansouzak** [comment]
1 - Seu model de message n tem esse metodo: https://github.com/joaoclopes/wrkoo/blob/1977b5f777ba6d55023da02fc8f772a5d1ce8aee/Models/Message.php
2 - A model como o nome ja diz serve de modelo pra algo, não é responsabilidade dela consultar mensagens

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit
