### ISSUE TITLE
QUE?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#38]
https://github.com/joaoclopes/wrkoo/blob/1977b5f777ba6d55023da02fc8f772a5d1ce8aee/Service/MessageService.php#L18

Qual logica aqui?
N seria so validar se o sender é igual o receiver pq tem um monte de negação na frente, dificultar a leitura e manutenção disso

**Comment by joaoclopes** [comment]
Arrumei la, quando subir o commit anexo aqui

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit
