### ISSUE TITLE
$this? da onde isso?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#39]
https://github.com/joaoclopes/wrkoo/blob/1977b5f777ba6d55023da02fc8f772a5d1ce8aee/Service/UserService.php#L9

da onde vc ta tirando essas propriedades com this?

**Comment by joaoclopes** [comment]
Da model mesmo, é errado chamar aqui?

**Comment by jeansouzak** [comment]
```
$this é a model?
```
https://www.php.net/manual/en/language.oop5.basic.php

**Comment by joaoclopes** [comment]
https://github.com/joaoclopes/wrkoo/commit/ff97c7db1c3b848804cb086ab2b2a9915f45e746
Ajsutado nesse commit
