### ISSUE TITLE
Pq a service precisa deste objeto na sua criação?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#4]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Controller/MessageController.php#L22

Se vc precisar de um objeto de mensagem na criação vc presume q este objeto será reutirlizado no objeto message service como um todo, não é uma boa pratica, normalmente seus metodos devem receber os objetos e dependencias, são raras dependencias de services e caso hajam o interessante é ter um Dependency Injection / Inversion of control para resolver isso para ti

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
