### ISSUE TITLE
pq essa validação está solta?

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#5]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Controller/MessageController.php#L24

O que essa validação irá fazer?
Vc n precisa testar isso de alguma forma em um if ou pelo menos um bloco try catch com o throws dentro do metodo q esta sendo chamado

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
