### ISSUE TITLE
Repository deve ser chamado pela sua service

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#7]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Controller/MessageController.php#L29

Você deveria ter um metodo de registro na service que recebe esse objeto e chama a repository para inserção...

**Comment by joaoclopes** [comment]
esse código ta no lugar errado, era no user nao no message
