### ISSUE TITLE
Mesma questão do outro service

### ISSUE THREAD

**Issue by jeansouzak** [joaoclopes/wrkoo#9]
https://github.com/joaoclopes/wrkoo/blob/e8c7b2a0b0b9e154082a24fa8dd4470387de0b9c/Controller/UserController.php#L13

Mesma questão da issue: https://github.com/joaoclopes/wrkoo/issues/4

**Comment by joaoclopes** [comment]
Ajustado nesse commit
https://github.com/joaoclopes/wrkoo/commit/feb94c2fb1f9234ae95327803b46b800505f27f8
